config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
 
get "about" => "pages#about.html.erb"

get "add" => "pages#addproject.html.erb"
  
get "build" => "pages#build.html.erb"

get "community" => "pages#community.html.erb"

get "contribute" => "pages#contribute.html.erb"

get "disease" => "pages#disease.html.erb"

get "geography" => "pages#geography.html.erb"

get "keywords" => "pages#keywords.html.erb"

get "maps" => "pages#maps.html.erb"

get "project" => "pages#project.html.erb"

get "search" => "pages#search.html.erb"

get "addurl" => "pages#addurl.html.erb"

get "login" => "pages#login.html.erb"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def geography
  end

  def add
  end

  def maps
  end

  def search
  end

  def about
  end

  def contribute
  end

  def project
  end

  def disease
  end

  def keywords
  end

  def build
  end

  def community
  end

  def addurl
  end
  
  def login
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="container">
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Open Health Map", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><li><%= link_to "Home", root_path %><span class="sr-only">(current)</span></li>
       
       <li><%= link_to "Add", add_path %></li>
      
       <li><%= link_to "Search", search_path %></li>
        <li class="Maps">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Maps <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Geography", geography_path %></li> 
            <li><%= link_to "Disease", disease_path %></li> 
            <li><%= link_to "Project", project_path %></li> 
            <li role="separator" class="divider"></li>
         		 <li><%= link_to "Keywords", keywords_path %></li>
          </ul>
        </li>
      </ul>



      <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Login", login_path %></li>
      <li class="About">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About <span class="caret"></span></a>
          <ul class="dropdown-menu">
           <li><%= link_to "About", about_path %></li>
           <li><%= link_to "Build", build_path %></li>
           <li><%= link_to "Community", community_path %></li>
        
          </ul>
        </li>
        
       
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div> <!-- / .container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Openhealthmap</title>

		<%= csrf_meta_tags %>

	    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    	<meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>

	<%= render 'layouts/header' %>

  <body>

     <div class="container">
		
     <%= yield %>
     </div>
   
  </body>
</html>

app/views/pages/addproject.html.erb
<body>
<div class="jumbotron">
  <div class="container">
  
 
<div class="jumbotron">
  <div class="container">

   <h2> Add a Project </h2>
  </span> 
  </button>

<p> 
<br>
  </p>


<div class="row">
  <div class="col-lg-6">
    <div class="input-group">
      <span class="input-group-btn">  
        <%= link_to "Project Name", "#", class: "btn btn-info btn" %> 
        </span>  
     <input type="text" class="form-control" placeholder="Project Name"> 
     </span>
      
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->

<p>
  <br>
</p>

<div class="row">
  <div class="col-lg-6">
    <div class="input-group">
      <span class="input-group-btn">  
        <%= link_to "Add URL", "#", class: "btn btn-default btn" %> 
        </span>  
     <input type="text" class="form-control" placeholder="http://"> 
     </span>
      
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->

 <p> 
<br>
  </p>

  
  <div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Location
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <li><%= link_to "Africa", "#" %> </li>
    <li><%= link_to "Asia", "#" %> </li>
    <li><%= link_to "Australia/NZ", "#" %> </li>
    <li><%= link_to "Europe", "#" %> </li>
    <li><%= link_to "North America", "#" %> </li>
    <li><%= link_to "South America", "#" %> </li>
    <li role="separator" class="divider"></li>
    <li><%= link_to "Global", "#" %> </li>
  </ul> <!-- /ends location button -->
</div> <!-- /ends location dropdown -->

<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Type of OS Project <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "OSS", "#" %> </li>
    <li><%= link_to "OSHW", "#" %> </li>
    <li><%= link_to "OSS/OSHW", "#" %> </li>
    <li><%= link_to "OS Project/Initiative", "#" %> </li>
    <li><%= link_to "DIY", "#" %> </li>
    <li><%= link_to "Open Design", "#" %> </li>
    <li role="separator" class="divider"></li>
    <li><%= link_to "Other", "#" %> </li>
  </ul> <!-- /ends type button -->
</div> <!-- /ends type dropdown -->

<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Function <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "Wellness/Self Care", "#" %> </li>
    <li><%= link_to "Diagnostic", "#" %> </li>
    <li><%= link_to "Treatment", "#" %> </li>
    <li><%= link_to "Hospital Devices", "#" %> </li>
    <li><%= link_to "Infrastructure:EMR", "#" %> </li>
    <li><%= link_to "Supply Chain", "#" %> </li>
    <li><%= link_to "Provider/Service Referral", "#" %> </li>
    <li><%= link_to "Payments/Insurance", "#" %> </li>
    <li role="separator" class="divider"></li>
    <li><%= link_to "Other", "#" %> </li>
  </ul> <!-- /ends function button -->
</div> <!-- /ends function dropdown -->

<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Business Model <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "Freeware", "#" %> </li>
    <li><%= link_to "Non-Profit", "#" %> </li>
    <li><%= link_to "Freemium", "#" %> </li>
    <li><%= link_to "For Profit", "#" %> </li>
    <li><%= link_to "Academic", "#" %> </li>
    <li><%= link_to "Government", "#" %> </li>
    <li role="separator" class="divider"></li>
    <li><%= link_to "Other", "#" %> </li>
  </ul> <!-- /ends biz model button -->
</div> <!-- /ends biz model dropdown -->

<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Status <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "Active", "#" %> </li>
    <li><%= link_to "Maintained", "#" %> </li>
    <li><%= link_to "Dormant", "#" %> </li>
    <li><%= link_to "Unknown", "#" %> </li>
  </ul> <!-- /ends status button -->
</div> <!-- /ends status dropdown -->

<p> 
<br>
  </p>


 
<div class="row">
  <div class="col-lg-6">
    <div class="input-group">
      <span class="input-group-btn">  
        <%= link_to "Tags", "#", class: "btn btn-success btn" %> 
        </span>  
     <input type="text" class="form-control" placeholder="Keywords"> 
     </span>
      
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->

 <div class="row">
  <div class="col-lg-6">
    <div class="input-group">
      <span class="input-group-btn">
         <%= link_to "Add Project", "#", class: "btn btn-primary btn" %> 
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->

  



 

  
  

app/views/pages/addurl.html.erb
<body>
<div class="jumbotron">
  <div class="container">

  <button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-plus" aria-hidden="true">
    Add a Project
  </span> 
  </button>

  <p> 
  	<div class="row">
  <div class="col-lg-6">
    <div class="input-group">
      <span class="input-group-btn">
         <%= link_to "Add a project", "#", class: "btn btn-primary btn" %> 
      </span>
      <input type="text" class="form-control" placeholder="enter the project URL">
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->

app/views/pages/geography.html.erb
	
<h1>Open Source Health Map</h1>
<h2>mapping open source projects in health care</h2>

app/views/pages/home.html.erb
<div class="jumbotron center">
<div class="container">
<h1>Open Health Map</h1> 
<p>
We are mapping open source projects in health care
<br>
</p>

<body>
  
  <p>
<br>
</p>
  	<div class="row">
  <div class="col-lg-6">
    <div class="input-group">
      <span class="input-group-btn">
         <%= link_to "Add a project", "#", class: "btn btn-primary btn" %> 
      </span>
      <input type="text" class="form-control" placeholder="enter the project URL">
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->

  <div class="col-lg-6">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Keyword Search OS Projects in Health...">
      <span class="input-group-btn">
        <%= link_to "View Projects", "#", class: "btn btn-warning btn" %> 
       
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->
  </p>
     
  </div>

</div>
	
</body>

app/views/pages/login.html.erb
<div class="jumbotron center">
     <h1>Open Health Map</h1>
<p>
We are mapping open source projects in health care
<br>
</p>
     <p>
       <%= link_to "Log in", "#", class: "btn btn-success btn-lg" %>
       <%= link_to "Sign up", "#", class: "btn btn-primary btn-lg" %>
  </p>    
</div>

app/views/pages/maps.html.erb
maps

app/views/pages/search.html.erb
<body>
<div class="jumbotron">
  <div class="container">
  
 

<div class="jumbotron">
  <div class="container">

   <h2> Search Projects </h2>
  </span> 
  </button>

<p> 
<br>
  </p>

<div class="row">
  <div class="col-lg-6">
    <div class="input-group">
      <span class="input-group-btn">  
        <%= link_to "Project Name", "#", class: "btn btn-info btn" %> 
        </span>  
     <input type="text" class="form-control" placeholder="Project Name"> 
     </span>
      
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->

  <p> 
<br>
  </p>

  
  <div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Location
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <li><%= link_to "Africa", "#" %> </li>
    <li><%= link_to "Asia", "#" %> </li>
    <li><%= link_to "Australia/NZ", "#" %> </li>
    <li><%= link_to "Europe", "#" %> </li>
    <li><%= link_to "North America", "#" %> </li>
    <li><%= link_to "South America", "#" %> </li>
    <li role="separator" class="divider"></li>
    <li><%= link_to "Global", "#" %> </li>
  </ul> <!-- /ends location button -->
</div> <!-- /ends location dropdown -->

<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Type of OS Project <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "OSS", "#" %> </li>
    <li><%= link_to "OSHW", "#" %> </li>
    <li><%= link_to "OSS/OSHW", "#" %> </li>
    <li><%= link_to "OS Project/Initiative", "#" %> </li>
    <li><%= link_to "DIY", "#" %> </li>
    <li><%= link_to "Open Design", "#" %> </li>
    <li role="separator" class="divider"></li>
    <li><%= link_to "Other", "#" %> </li>
  </ul> <!-- /ends type button -->
</div> <!-- /ends type dropdown -->

<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Function <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "Wellness/Self Care", "#" %> </li>
    <li><%= link_to "Diagnostic", "#" %> </li>
    <li><%= link_to "Treatment", "#" %> </li>
    <li><%= link_to "Hospital Devices", "#" %> </li>
    <li><%= link_to "Infrastructure:EMR", "#" %> </li>
    <li><%= link_to "Supply Chain", "#" %> </li>
    <li><%= link_to "Provider/Service Referral", "#" %> </li>
    <li><%= link_to "Payments/Insurance", "#" %> </li>
    <li role="separator" class="divider"></li>
    <li><%= link_to "Other", "#" %> </li>
  </ul> <!-- /ends function button -->
</div> <!-- /ends function dropdown -->

<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Business Model <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "Freeware", "#" %> </li>
    <li><%= link_to "Non-Profit", "#" %> </li>
    <li><%= link_to "Freemium", "#" %> </li>
    <li><%= link_to "For Profit", "#" %> </li>
    <li><%= link_to "Academic", "#" %> </li>
    <li><%= link_to "Government", "#" %> </li>
    <li role="separator" class="divider"></li>
    <li><%= link_to "Other", "#" %> </li>
  </ul> <!-- /ends biz model button -->
</div> <!-- /ends biz model dropdown -->

<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Status <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "Active", "#" %> </li>
    <li><%= link_to "Maintained", "#" %> </li>
    <li><%= link_to "Dormant", "#" %> </li>
    <li><%= link_to "Unknown", "#" %> </li>
  </ul> <!-- /ends status button -->
</div> <!-- /ends status dropdown -->

<p> 
<br>
</p>

 
<div class="row">
  <div class="col-lg-6">
    <div class="input-group">
      <span class="input-group-btn">  
        <%= link_to "Tags", "#", class: "btn btn-success btn" %> 
        </span>  
     <input type="text" class="form-control" placeholder="Keywords"> 
     </span>
      
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->

<div class="col-lg-6">
    <div class="input-group">
      <span class="input-group-btn">
        <%= link_to "View Projects", "#", class: "btn btn-warning btn" %> 
       
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->

  



 

  
  